### ISSUE TITLE
Internal Server Error on the Dashboard

### ISSUE THREAD

**Issue by joe2824** [staxDB/humhub-modules-external-calendar#8]
When I activate the Plugin my Dashboard doesn't work. It shows only the an error.
I can't disable or deinstall the Plugin on the website I have to delete the Plugin Folder via FTP.

<img width="1160" alt="bildschirmfoto 2018-04-14 um 17 57 00" src="https://user-images.githubusercontent.com/4028085/38770091-99c7eaa4-400d-11e8-8833-fcb05f160fa5.png">
<img width="863" alt="bildschirmfoto 2018-04-14 um 17 57 10" src="https://user-images.githubusercontent.com/4028085/38770092-9a691f78-400d-11e8-8b34-7d12db5247a4.png">

**Comment by staxDB** [comment]
Can you show me the error log? You can find it under ‚Administration->Information->Logging‘

Do you have also installed the humhub calendar module?

**Comment by staxDB** [comment]
there seems to be an issue regarding the calendar module v0.6.7. 
Nevertheless, I would be happy about the error log.

**Comment by joe2824** [comment]
```
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'joelklei_dlrg_hub.external_calendar_entry' doesn't exist in /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/db/Command.php:1258 Stack trace: #0 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/db/Command.php(1258): PDOStatement->execute() #1 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/db/Command.php(1148): yii\db\Command->internalExecute('SELECT `externa...') #2 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL) #3 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/db/Query.php(237): yii\db\Command->queryAll() #4 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(133): yii\db\Query->all(NULL) #5 /home/joelklei/ogdorheim.de/protected/modules/calendar/interfaces/AbstractCalendarQuery.php(566): yii\db\ActiveQuery->all() #6 /home/joelklei/ogdorheim.de/protected/modules/calendar/interfaces/AbstractCalendarQuery.php(143): humhub\modules\calendar\interfaces\AbstractCalendarQuery->all() #7 /home/joelklei/ogdorheim.de/protected/modules/calendar/interfaces/AbstractCalendarQuery.php(152): humhub\modules\calendar\interfaces\AbstractCalendarQuery::findForFilter(Object(DateTime), Object(DateTime), NULL, Array, '5') #8 /home/joelklei/ogdorheim.de/protected/modules/external-calendar/integration/calendar/CalendarExtension.php(42): humhub\modules\calendar\interfaces\AbstractCalendarQuery::findForEvent(Object(humhub\modules\calendar\interfaces\CalendarItemsEvent)) #9 /home/joelklei/ogdorheim.de/protected/modules/external-calendar/Events.php(38): humhub\modules\external_calendar\integration\calendar\CalendarExtension::addItems(Object(humhub\modules\calendar\interfaces\CalendarItemsEvent)) #10 [internal function]: humhub\modules\external_calendar\Events::onFindCalendarItems(Object(humhub\modules\calendar\interfaces\CalendarItemsEvent)) #11 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/base/Event.php(310): call_user_func(Array, Object(humhub\modules\calendar\interfaces\CalendarItemsEvent)) #12 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('humhub\\modules\\...', 'findItems', Object(humhub\modules\calendar\interfaces\CalendarItemsEvent)) #13 /home/joelklei/ogdorheim.de/protected/modules/calendar/interfaces/CalendarService.php(110): yii\base\Component->trigger('findItems', Object(humhub\modules\calendar\interfaces\CalendarItemsEvent)) #14 /home/joelklei/ogdorheim.de/protected/modules/calendar/interfaces/CalendarService.php(148): humhub\modules\calendar\interfaces\CalendarService->getCalendarItems(Object(DateTime), Object(DateTime), Array, NULL, '5') #15 /home/joelklei/ogdorheim.de/protected/modules/calendar/widgets/UpcomingEvents.php(41): humhub\modules\calendar\interfaces\CalendarService->getUpcomingEntries(NULL, '31', '5') #16 /home/joelklei/ogdorheim.de/protected/humhub/components/Widget.php(57): humhub\modules\calendar\widgets\UpcomingEvents->run() #17 /home/joelklei/ogdorheim.de/protected/humhub/widgets/BaseStack.php(85): humhub\components\Widget::widget(Array) #18 /home/joelklei/ogdorheim.de/protected/humhub/components/Widget.php(57): humhub\widgets\BaseStack->run() #19 /home/joelklei/ogdorheim.de/protected/humhub/modules/dashboard/views/dashboard/index.php(24): humhub\components\Widget::widget(Array) #20 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/base/View.php(336): require('/home/joelklei/...') #21 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/home/joelklei/...', Array) #22 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/joelklei/...', Array, Object(humhub\modules\dashboard\controllers\DashboardController)) #23 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/base/Controller.php(384): yii\base\View->render('index', Array, Object(humhub\modules\dashboard\controllers\DashboardController)) #24 /home/joelklei/ogdorheim.de/protected/humhub/modules/dashboard/controllers/DashboardController.php(69): yii\base\Controller->render('index', Array) #25 [internal function]: humhub\modules\dashboard\controllers\DashboardController->actionIndex() #26 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #27 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #28 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('', Array) #29 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('dashboard/dashb...', Array) #30 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #31 /home/joelklei/ogdorheim.de/index.php(25): yii\base\Application->run() #32 {main} Next yii\db\Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'joelklei_dlrg_hub.external_calendar_entry' doesn't exist The SQL being executed was: SELECT `external_calendar_entry`.* FROM `external_calendar_entry` LEFT JOIN `content` ON `external_calendar_entry`.`id` = `content`.`object_id` LEFT JOIN `contentcontainer` ON `content`.`contentcontainer_id` = `contentcontainer`.`id` LEFT JOIN `user` ON `content`.`created_by` = `user`.`id` LEFT JOIN `space` ON contentcontainer.pk=space.id AND contentcontainer.class='humhub\\modules\\space\\models\\Space' LEFT JOIN `user` `cuser` ON contentcontainer.pk=cuser.id AND contentcontainer.class='humhub\\modules\\user\\models\\User' LEFT JOIN `space_membership` ON contentcontainer.pk=space_membership.space_id AND contentcontainer.class='humhub\\modules\\space\\models\\Space' AND space_membership.user_id=1 WHERE (((`start_datetime` >= '2018-08-14 00:00:00') AND (`start_datetime` <= '2018-09-14 23:59:59')) OR ((`end_datetime` >= '2018-08-14 00:00:00') AND (`end_datetime` <= '2018-09-14 23:59:59'))) AND (space.id IS NOT NULL AND ( (space_membership.status=3) OR (content.visibility=1 AND space.visibility != 0)) OR cuser.id IS NOT NULL AND ( (content.visibility = 1) OR (content.visibility = 0 AND content.contentcontainer_id=1))OR content.created_by=1) AND ((contentcontainer.pk=1 AND class='humhub\\modules\\user\\models\\User') OR (contentcontainer.pk IN (SELECT `sm`.`id` FROM `space_membership` LEFT JOIN `space` `sm` ON sm.id=space_membership.space_id WHERE space_membership.user_id=1 AND space_membership.status=3) AND contentcontainer.class = 'humhub\\modules\\space\\models\\Space')) AND (`content`.`object_model`='humhub\\modules\\external_calendar\\models\\ExternalCalendarEntry') AND (`content`.`object_model`='humhub\\modules\\external_calendar\\models\\ExternalCalendarEntry') ORDER BY `start_datetime` LIMIT 5 in /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/db/Schema.php:664 Stack trace: #0 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'SELECT `externa...') #1 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/db/Command.php(1148): yii\db\Command->internalExecute('SELECT `externa...') #2 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL) #3 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/db/Query.php(237): yii\db\Command->queryAll() #4 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(133): yii\db\Query->all(NULL) #5 /home/joelklei/ogdorheim.de/protected/modules/calendar/interfaces/AbstractCalendarQuery.php(566): yii\db\ActiveQuery->all() #6 /home/joelklei/ogdorheim.de/protected/modules/calendar/interfaces/AbstractCalendarQuery.php(143): humhub\modules\calendar\interfaces\AbstractCalendarQuery->all() #7 /home/joelklei/ogdorheim.de/protected/modules/calendar/interfaces/AbstractCalendarQuery.php(152): humhub\modules\calendar\interfaces\AbstractCalendarQuery::findForFilter(Object(DateTime), Object(DateTime), NULL, Array, '5') #8 /home/joelklei/ogdorheim.de/protected/modules/external-calendar/integration/calendar/CalendarExtension.php(42): humhub\modules\calendar\interfaces\AbstractCalendarQuery::findForEvent(Object(humhub\modules\calendar\interfaces\CalendarItemsEvent)) #9 /home/joelklei/ogdorheim.de/protected/modules/external-calendar/Events.php(38): humhub\modules\external_calendar\integration\calendar\CalendarExtension::addItems(Object(humhub\modules\calendar\interfaces\CalendarItemsEvent)) #10 [internal function]: humhub\modules\external_calendar\Events::onFindCalendarItems(Object(humhub\modules\calendar\interfaces\CalendarItemsEvent)) #11 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/base/Event.php(310): call_user_func(Array, Object(humhub\modules\calendar\interfaces\CalendarItemsEvent)) #12 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('humhub\\modules\\...', 'findItems', Object(humhub\modules\calendar\interfaces\CalendarItemsEvent)) #13 /home/joelklei/ogdorheim.de/protected/modules/calendar/interfaces/CalendarService.php(110): yii\base\Component->trigger('findItems', Object(humhub\modules\calendar\interfaces\CalendarItemsEvent)) #14 /home/joelklei/ogdorheim.de/protected/modules/calendar/interfaces/CalendarService.php(148): humhub\modules\calendar\interfaces\CalendarService->getCalendarItems(Object(DateTime), Object(DateTime), Array, NULL, '5') #15 /home/joelklei/ogdorheim.de/protected/modules/calendar/widgets/UpcomingEvents.php(41): humhub\modules\calendar\interfaces\CalendarService->getUpcomingEntries(NULL, '31', '5') #16 /home/joelklei/ogdorheim.de/protected/humhub/components/Widget.php(57): humhub\modules\calendar\widgets\UpcomingEvents->run() #17 /home/joelklei/ogdorheim.de/protected/humhub/widgets/BaseStack.php(85): humhub\components\Widget::widget(Array) #18 /home/joelklei/ogdorheim.de/protected/humhub/components/Widget.php(57): humhub\widgets\BaseStack->run() #19 /home/joelklei/ogdorheim.de/protected/humhub/modules/dashboard/views/dashboard/index.php(24): humhub\components\Widget::widget(Array) #20 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/base/View.php(336): require('/home/joelklei/...') #21 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/home/joelklei/...', Array) #22 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/joelklei/...', Array, Object(humhub\modules\dashboard\controllers\DashboardController)) #23 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/base/Controller.php(384): yii\base\View->render('index', Array, Object(humhub\modules\dashboard\controllers\DashboardController)) #24 /home/joelklei/ogdorheim.de/protected/humhub/modules/dashboard/controllers/DashboardController.php(69): yii\base\Controller->render('index', Array) #25 [internal function]: humhub\modules\dashboard\controllers\DashboardController->actionIndex() #26 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #27 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #28 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('', Array) #29 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('dashboard/dashb...', Array) #30 /home/joelklei/ogdorheim.de/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #31 /home/joelklei/ogdorheim.de/index.php(25): yii\base\Application->run() #32 {main} Additional Information: Array ( [0] => 42S02 [1] => 1146 [2] => Table 'joelklei_dlrg_hub.external_calendar_entry' doesn't exist )
```

This is the actuaL error Log I use HH V1.3.1 with calendar 0.6.17

**Comment by staxDB** [comment]
It looks like your database migrations didn't work. The necessary tables were not created when the module was installed. 
Check your database to see if the tables `external_calendar_entry` and `external_calendar` exist.

If they doesn't exists, try using this in your server-terminal:
```
php yii migrate/up --includeModuleMigrations=1
```

**Comment by ggrraaff** [comment]
same issue here
tried terminal but no effect

porotocol says:
 ReflectionException: Class humhub\modules\external_calendar\models\ExternalCalendarEntry does not exist in /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/di/Container.php:428 Stack trace: #0 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/di/Container.php(428): ReflectionClass->__construct('humhub\\modules\\...') #1 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/di/Container.php(364): yii\di\Container->getDependencies('humhub\\modules\\...') #2 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('humhub\\modules\\...', Array, Array) #3 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/BaseYii.php(345): yii\di\Container->get('humhub\\modules\\...', Array) #4 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/humhub/modules/content/models/ContentType.php(46): yii\BaseYii::createObject('humhub\\modules\\...') #5 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\modules\content\models\ContentType->init() #6 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/humhub/modules/content/models/ContentType.php(71): yii\base\BaseObject->__construct(Array) #7 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/humhub/modules/content/models/ContentType.php(83): humhub\modules\content\models\ContentType::getContentTypes(NULL) #8 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/humhub/modules/content/widgets/ContentTypePicker.php(41): humhub\modules\content\models\ContentType::getContentTypeSelection(NULL) #9 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\modules\content\widgets\ContentTypePicker->init() #10 [internal function]: yii\base\BaseObject->__construct(Array) #11 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array) #12 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('humhub\\modules\\...', Array, Array) #13 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('humhub\\modules\\...', Array, Array) #14 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/humhub/components/Widget.php(54): yii\BaseYii::createObject(Array) #15 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/humhub/modules/ui/filter/widgets/views/pickerInput.php(14): humhub\components\Widget::widget(Array) #16 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/base/View.php(336): require('/www/htdocs/w00...') #17 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/www/htdocs/w00...', Array) #18 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/www/htdocs/w00...', Array, Object(humhub\modules\ui\filter\widgets\PickerFilterInput)) #19 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/base/Widget.php(236): yii\base\View->render('pickerInput', Array, Object(humhub\modules\ui\filter\widgets\PickerFilterInput)) #20 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/humhub/modules/ui/filter/widgets/FilterInput.php(76): yii\base\Widget->render('pickerInput', Array) #21 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/humhub/components/Widget.php(57): humhub\modules\ui\filter\widgets\FilterInput->run() #22 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/humhub/modules/ui/filter/widgets/views/filterListBlock.php(24): humhub\components\Widget::widget(Array) #23 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/base/View.php(336): require('/www/htdocs/w00...') #24 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/www/htdocs/w00...', Array) #25 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/www/htdocs/w00...', Array, Object(humhub\modules\ui\filter\widgets\FilterBlock)) #26 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/base/Widget.php(236): yii\base\View->render('filterListBlock', Array, Object(humhub\modules\ui\filter\widgets\FilterBlock)) #27 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/humhub/modules/ui/filter/widgets/FilterBlock.php(64): yii\base\Widget->render('filterListBlock', Array) #28 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/humhub/components/Widget.php(57): humhub\modules\ui\filter\widgets\FilterBlock->run() #29 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/humhub/modules/ui/filter/widgets/views/filterPanel.php(21): humhub\components\Widget::widget(Array) #30 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/base/View.php(336): require('/www/htdocs/w00...') #31 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/www/htdocs/w00...', Array) #32 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/www/htdocs/w00...', Array, Object(humhub\modules\ui\filter\widgets\FilterPanel)) #33 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/base/Widget.php(236): yii\base\View->render('filterPanel', Array, Object(humhub\modules\ui\filter\widgets\FilterPanel)) #34 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/humhub/modules/ui/filter/widgets/FilterPanel.php(41): yii\base\Widget->render('filterPanel', Array) #35 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/humhub/components/Widget.php(57): humhub\modules\ui\filter\widgets\FilterPanel->run() #36 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/humhub/modules/stream/widgets/views/wallStreamFilterNavigation.php(37): humhub\components\Widget::widget(Array) #37 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/base/View.php(336): require('/www/htdocs/w00...') #38 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/www/htdocs/w00...', Array) #39 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/www/htdocs/w00...', Array, Object(humhub\modules\stream\widgets\WallStreamFilterNavigation)) #40 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/base/Widget.php(236): yii\base\View->render('wallStreamFilte...', Array, Object(humhub\modules\stream\widgets\WallStreamFilterNavigation)) #41 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/humhub/modules/ui/filter/widgets/FilterNavigation.php(150): yii\base\Widget->render('wallStreamFilte...', Array) #42 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/humhub/components/Widget.php(57): humhub\modules\ui\filter\widgets\FilterNavigation->run() #43 [internal function]: humhub\components\Widget::widget(Array) #44 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/humhub/modules/stream/widgets/StreamViewer.php(170): call_user_func('humhub\\modules\\...', Array) #45 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/humhub/components/Widget.php(57): humhub\modules\stream\widgets\StreamViewer->run() #46 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/humhub/widgets/BaseStack.php(85): humhub\components\Widget::widget(Array) #47 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/humhub/components/Widget.php(57): humhub\widgets\BaseStack->run() #48 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/humhub/modules/dashboard/views/dashboard/index.php(24): humhub\components\Widget::widget(Array) #49 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/base/View.php(336): require('/www/htdocs/w00...') #50 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/www/htdocs/w00...', Array) #51 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/www/htdocs/w00...', Array, Object(humhub\modules\dashboard\controllers\DashboardController)) #52 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/base/Controller.php(384): yii\base\View->render('index', Array, Object(humhub\modules\dashboard\controllers\DashboardController)) #53 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/humhub/modules/dashboard/controllers/DashboardController.php(69): yii\base\Controller->render('index', Array) #54 [internal function]: humhub\modules\dashboard\controllers\DashboardController->actionIndex() #55 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #56 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #57 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('', Array) #58 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('dashboard/dashb...', Array) #59 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #60 /www/htdocs/w00afb8e/institut.literaturinstitut-hildesheim.de/index.php(25): yii\base\Application->run() #61 {main}
